# Generated by Django 5.0.6 on 2024-05-21 10:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='only_medias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'avi', 'mov', 'gif', 'webp', 'pdf', 'doc', 'docx', 'mpeg'])], verbose_name='File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'document'), ('gif', 'Gif'), ('other', 'Other')], max_length=10, verbose_name='File Type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='StandardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_phone_number', models.CharField(max_length=150, verbose_name='Main phone number')),
                ('main_email', models.CharField(max_length=150, verbose_name='Main email')),
                ('instagram', models.CharField(max_length=150, verbose_name='Instagram')),
                ('vkontakte', models.CharField(max_length=150, verbose_name='VK')),
            ],
            options={
                'verbose_name': 'Standard Settings',
            },
        ),
        migrations.CreateModel(
            name='BackgroundImage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Background Image')),
                ('bottom_text', models.CharField(max_length=250, verbose_name='Bottom text')),
                ('back_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_image1', to='common.media', verbose_name='Background Image')),
            ],
            options={
                'verbose_name': 'Background Image One',
            },
        ),
        migrations.CreateModel(
            name='AboutUs2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150, verbose_name='Headline')),
                ('text', models.TextField(verbose_name='Text')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_image2', to='common.media', verbose_name='Image')),
            ],
            options={
                'verbose_name': "Second 'About us' page",
            },
        ),
        migrations.CreateModel(
            name='AboutUs1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150, verbose_name='Headline')),
                ('text', models.TextField(verbose_name='Text')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_image1', to='common.media', verbose_name='Image')),
            ],
            options={
                'verbose_name': "First 'About us' page",
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150, verbose_name='Headline')),
                ('text', models.TextField(verbose_name='Text')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_image', to='common.media', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Promo',
            },
        ),
    ]
