# Generated by Django 5.0.6 on 2024-05-23 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('surname', models.CharField(max_length=120, verbose_name='Surname')),
                ('street', models.CharField(max_length=120, verbose_name='Street')),
                ('house', models.CharField(max_length=12, verbose_name='House')),
                ('apartment', models.CharField(blank=True, max_length=12, verbose_name='Apartment')),
                ('delivery_date', models.DateField(verbose_name='Delivery date')),
                ('delivery_time', models.TimeField(verbose_name='Delivery Time')),
                ('status', models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('progress', 'progress'), ('cancelled', 'cancelled'), ('finished', 'finished')], default='new', max_length=20, verbose_name='status')),
                ('payment', models.CharField(choices=[('credit_card', 'Credit card'), ('cash', 'Cash')], max_length=120, verbose_name='Payment method')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='The reason of return')),
            ],
            options={
                'verbose_name': 'Return',
            },
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorywomen',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productwomen',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='size_letter',
        ),
        migrations.RemoveField(
            model_name='productmen',
            name='size_num',
        ),
        migrations.RemoveField(
            model_name='productwomen',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productwomen',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productwomen',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productwomen',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productwomen',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productwomen',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='productwomen',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='productwomen',
            name='size_letter',
        ),
        migrations.RemoveField(
            model_name='productwomen',
            name='size_num',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='common.media', verbose_name='Category image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('price', models.FloatField(verbose_name='Price')),
                ('discounted_price', models.FloatField(default=0, verbose_name='Discounted price')),
                ('description', models.TextField(verbose_name='Description')),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=120, verbose_name='Men/Women')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_product_women', to='shop.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='shop.category', verbose_name='Category')),
                ('colors', models.ManyToManyField(to='common.media', verbose_name='Colors')),
                ('image1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='common.media', verbose_name='Image 1')),
                ('image2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image2', to='common.media', verbose_name='Image 2')),
                ('image3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image3', to='common.media', verbose_name='Image 3')),
                ('image4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image4', to='common.media', verbose_name='Image 4')),
                ('image5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image5', to='common.media', verbose_name='Image 5')),
                ('size_letter', models.ManyToManyField(to='shop.productsizeletter', verbose_name='Size in letters')),
                ('size_num', models.ManyToManyField(to='shop.productsizenumerical', verbose_name='Size in numbers')),
            ],
            options={
                'verbose_name': 'Product for women',
                'verbose_name_plural': 'Products for women',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order item',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='CategoryMen',
        ),
        migrations.DeleteModel(
            name='CategoryWomen',
        ),
        migrations.DeleteModel(
            name='ProductMen',
        ),
        migrations.DeleteModel(
            name='ProductWomen',
        ),
    ]
